swagger: "2.0"
info:
  version: 1.0.0
  title: X.Scraper
host: localhost
basePath: /v1
schemes:
  - http
produces:
  - application/json
security: []
paths:
  /proxy:
    get:
      summary: Get proxies by a protocol
      x-swagger-router-controller: ProxyController
      operationId: getProxy
      parameters:
        - in: query
          name: protocol
          required: false
          description: Name(s) of the preferred protocol(s)
          type: array
          items:
            type: string
            enum: ["HTTPS","HTTP","SOCKS5"]
        - in: query
          name: limit
          required: false
          description: Number of proxies
          type: integer
        - in: query
          name: offset
          required: false
          description: Position to start result from
      responses:
        "200":
          description: Proxy list
          schema:
            type: array
            items:
              $ref: '#/definitions/Proxy'
definitions:
  Proxy:
    properties:
      server:
        type: string
        x-isnullable: false
        example: "192.168.0.12"
      port:
        type: number
        format: integer
        x-isnullable: false
        example: 1080
      iso_code:
        type: string
        x-isnullable: false
        example: "CN"
      country:
        type: string
        x-isnullable: false
        example: "China"
      protocol:
        type: string
        x-isnullable: false
        example: "SOCKS5"
        enum: ["HTTPS", "HTTP", "SOCKS5"]
      ping_time_ms:
        type: integer
        format: int
        x-isnullable: false
        example: 2500
      loss_ratio:
        type: number
        format: double
        x-isnullable: false
        example: 0.3333333

